seed: 42
amp: true
pretrained_model: microsoft/deberta-v3-base

datamodule:
  train_path: D:/dev/ML-ESG_codes/data/eng.parquet
  val_path: D:/dev/ML-ESG_codes/data/eng_val.parquet
  tokenizer_name: null
  use_title: true
  use_cls_weight: false
  batch_size: 4

model:
  model_name: null
  classifier_dropout: 0.3
  hidden_size: 256
  num_labels: null

train:
  learning_rate: 3e-5
  num_epochs: 3

callbacks:
  monitor: "val_loss"