seed: -
pretrained_model: microsoft/deberta-v3-base

datamodule:
  train_path: train_data.parquet
  val_path: /valid_data.parquet
  tokenizer_name: null
  use_title: true
  use_cls_weight: true
  batch_size: 32

model:
  model_name: null
  classifier_dropout: 0.3
  hidden_size: 256
  num_labels: null

train:
  learning_rate: 3e-5
  num_epochs: 15
  val_check_interval: 0.5

callbacks:
  mode: "min"
  monitor: "train_loss"