LABEL_IDX_DICT = {
    "Access to Finance": 0,
    "Carbon Emissions": 1,
    "Product Safety & Quality": 2,
    "Packaging Material & Waste": 3,
    "Ownership & Control": 4,
    "Opportunities in Renewable Energy": 5,
    "Human Capital Development": 6,
    "Access to Health Care": 7,
    "Water Stress": 8,
    "Board": 9,
    "Product Carbon Footprint": 10,
    "Responsible Investment": 11,
    "Accounting": 12,
    "Business Ethics": 13,
    "Opportunities in Nutrition & Health": 14,
    "Toxic Emissions & Waste": 15,
    "Opportunities in Green Building": 16,
    "Consumer Financial Protection": 17,
    "Opportunities in Clean Tech": 18,
    "Biodiversity & Land Use": 19,
    "Access to Communications": 20,
    "Climate Change Vulnerability": 21,
    "Pay": 22,
    "Raw Material Sourcing": 23,
    "Financing Environmental Impact": 24,
    "Community Relations": 25,
    "Chemical Safety": 26,
    "Labor Management": 27,
    "Electronic Waste": 28,
    "Supply Chain Labor Standards": 29,
    "Privacy & Data Security": 30,
    "Health & Demographic Risk": 31,
    "Controversial Sourcing": 32,
    "Health & Safety": 33,
    "Tax Transparency": 34,
}

IDX_LABEL_DICT = {idx: label for label, idx in LABEL_IDX_DICT.items()}
